<a href="https://colab.research.google.com/github/skymined/study_AIs/blob/main/docs/quests/MLs/SpineSurgeryList_FeatureEngin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quest
- SpineSurgeryList dataset 사용
- 목표변수(재발여부)
- 설명변수(최소 7개, 범주형 최소 2개)

## 데이터

In [5]:
import pandas as pd
import numpy as np
df_SSL = pd.read_csv('SpineSurgeryList.csv')
df_SSL[:4]

Unnamed: 0 환자ID  Large Lymphocyte  Location of herniation   ODI  가족력  \
0           0  1PT              22.8                       3  51.0  0.0   
1           1  2PT              44.9                       4  26.0  0.0   
2           2  3PT              53.0                       3   NaN  0.0   
3           3  4PT              54.7                       4  18.0  0.0   

   간질성폐질환  고혈압여부  과거수술횟수  당뇨여부  ...  Modic change    PI    PT  Seg Angle(raw)  \
0       0      0       0     0  ...             3  51.6  36.6            14.4   
1       0      0       0     0  ...             0  40.8   7.2            17.8   
2       0      0       1     0  ...             0  67.5  27.3            10.2   
3       0      1       0     0  ...             0  49.2  18.7            19.9   

   Vaccum disc   골밀도  디스크단면적  디스크위치  척추이동척도  척추전방위증  
0            0 -1.01  2048.5      4    Down       0  
1            0 -1.14  1753.1      4      Up       0  
2            0 -1.77  1749.0      4    Down       0  
3            0 -1.58  1796.2      4    Down       0  

[4 rows x 52 columns]

In [3]:
df_SSL.columns

Index(['Unnamed: 0', '환자ID', 'Large Lymphocyte', 'Location of herniation',
       'ODI', '가족력', '간질성폐질환', '고혈압여부', '과거수술횟수', '당뇨여부', '말초동맥질환여부', '빈혈여부',
       '성별', '스테로이드치료', '신부전여부', '신장', '심혈관질환', '암발병여부', '연령', '우울증여부', '입원기간',
       '입원일자', '종양진행여부', '직업', '체중', '퇴원일자', '헤모글로빈수치', '혈전합병증여부', '환자통증정도',
       '흡연여부', '통증기간(월)', '수술기법', '수술시간', '수술실패여부', '수술일자', '재발여부', '혈액형',
       '전방디스크높이(mm)', '후방디스크높이(mm)', '지방축적도', 'Instability', 'MF + ES',
       'Modic change', 'PI', 'PT', 'Seg Angle(raw)', 'Vaccum disc', '골밀도',
       '디스크단면적', '디스크위치', '척추이동척도', '척추전방위증'],
      dtype='object')

In [13]:
df_SSL[['재발여부', '성별', '연령','체중', '입원기간', '환자통증정도', '흡연여부', '과거수술횟수']].describe()
# 범주형 : 성별, 환자통증정도, 흡연여부, 과거수술횟수
# 수치형 : 연령, 체중, 입원기간

재발여부           성별           연령           체중         입원기간  \
count  1894.000000  1894.000000  1894.000000  1894.000000  1894.000000   
mean      0.119852     1.383316    41.463569    68.111140     1.736536   
std       0.324874     0.486323    13.444629    11.234318     2.344085   
min       0.000000     1.000000    15.000000    35.000000     0.000000   
25%       0.000000     1.000000    32.000000    59.700000     1.000000   
50%       0.000000     1.000000    41.000000    68.000000     1.000000   
75%       0.000000     2.000000    49.000000    75.000000     2.000000   
max       1.000000     2.000000    86.000000   136.100000    51.000000   

            환자통증정도         흡연여부       과거수술횟수  
count  1894.000000  1894.000000  1894.000000  
mean      6.884372     0.217001     0.302534  
std       2.075907     0.412312     0.638461  
min       1.000000     0.000000     0.000000  
25%       7.000000     0.000000     0.000000  
50%       7.000000     0.000000     0.000000  
75%       8.000000     0.000000     0.000000  
max      10.000000     1.000000     3.000000

In [15]:
# 결측치 확인 -> 결측치 없으므로 그대로 진행
df_SSL[['재발여부', '성별', '연령','체중', '입원기간', '환자통증정도', '흡연여부', '과거수술횟수']].isnull().sum()

재발여부      0
성별        0
연령        0
체중        0
입원기간      0
환자통증정도    0
흡연여부      0
과거수술횟수    0
dtype: int64

### Scaling - MinMax
- 수치형 : 연령, 체중, 입원기간

In [43]:
from sklearn.preprocessing import MinMaxScaler

def makescaling(dataframe, data) :
  minmax = MinMaxScaler()
  minmax.fit(dataframe[data].values.reshape(-1,1))
  result = minmax.transform(dataframe[data].values.reshape(-1,1))
  return result

In [35]:
df_SSL['연령'].value_counts()

47    106
48     82
46     73
39     73
38     63
     ... 
78      2
82      1
15      1
86      1
80      1
Name: 연령, Length: 68, dtype: int64

In [46]:
df_SSL['연령_scaling'] = makescaling(df_SSL,'연령')
df_SSL['연령_scaling'].describe() # 확인해봤으니 나머지 수치형도 대입

count    1894.000000
mean        0.372726
std         0.189361
min         0.000000
25%         0.239437
50%         0.366197
75%         0.478873
max         1.000000
Name: 연령_scaling, dtype: float64

In [47]:
df_SSL['체중_scaling'] = makescaling(df_SSL,'체중')
df_SSL['입원기간_scaling'] = makescaling(df_SSL,'입원기간')

### Onehot Encoding
- 범주형 : 성별, 환자통증정도, 흡연여부, 과거수술횟수

In [50]:
# unique를 위한 함수 제작해보기ㅋㅅㅋ
def knowunique(dataset, columns) :
  result = dataset[columns].unique()
  return result

In [51]:
knowunique(df_SSL, '성별')

array([2, 1])

In [52]:
knowunique(df_SSL, '환자통증정도')

array([10,  7,  8,  9,  2,  1,  6,  5,  3,  4])

In [53]:
knowunique(df_SSL, '흡연여부')

array([0, 1])

In [54]:
knowunique(df_SSL, '과거수술횟수')

array([0, 1, 2, 3])

In [57]:
from sklearn.preprocessing import OneHotEncoder
def onehot(dataset, columns) :
  hothot = OneHotEncoder()
  hothot.fit(dataset[[columns]])
  hothot.categories_ # array 생성하겠지?
  hothot.get_feature_names_out() # 각각의 array에 이름을 생성해요
  encoder_hothot = hothot.transform(dataset[[columns]]).toarray()
  df_encoder_hothot = pd.DataFrame(data=encoder_hothot, columns=hothot.get_feature_names_out())
  # 이제 행으로 concat
  dataset = pd.concat((dataset.reset_index(drop=True), dataset.reset_index(drop=True)), axis=1)
  return dataset

In [58]:
df_SSL = onehot(df_SSL, '성별')

In [59]:
df_SSL

Unnamed: 0    환자ID  Large Lymphocyte  Location of herniation   ODI  가족력  \
0              0     1PT              22.8                       3  51.0  0.0   
1              1     2PT              44.9                       4  26.0  0.0   
2              2     3PT              53.0                       3   NaN  0.0   
3              3     4PT              54.7                       4  18.0  0.0   
4              4     5PT              53.8                       4   NaN  0.0   
...          ...     ...               ...                     ...   ...  ...   
1889        1889  1890PT              44.0                       1   NaN  0.0   
1890        1890  1891PT              30.8                       2   NaN  0.0   
1891        1891  1892PT              36.7                       3   NaN  0.0   
1892        1892  1893PT              32.5                       2   NaN  0.0   
1893        1893  1894PT              49.5                       2   NaN  0.0   

      간질성폐질환  고혈압여부  과거수술횟수  당뇨여부  ...  Seg Angle(raw)  Vaccum disc   골밀도  \
0          0      0       0     0  ...            14.4            0 -1.01   
1          0      0       0     0  ...            17.8            0 -1.14   
2          0      0       1     0  ...            10.2            0 -1.77   
3          0      1       0     0  ...            19.9            0 -1.58   
4          0      1       0     0  ...             5.2            0 -0.79   
...      ...    ...     ...   ...  ...             ...          ...   ...   
1889       0      0       0     0  ...            21.8            0   NaN   
1890       0      0       0     0  ...             5.0            0   NaN   
1891       0      0       0     0  ...            17.4            1   NaN   
1892       0      0       0     0  ...            17.7            0   NaN   
1893       0      0       0     0  ...            27.8            0   NaN   

       디스크단면적  디스크위치  척추이동척도  척추전방위증  연령_scaling  체중_scaling  입원기간_scaling  
0     2048.50      4    Down       0    0.718310    0.250247      0.039216  
1     1753.10      4      Up       0    0.450704    0.363007      0.019608  
2     1749.00      4    Down       0    0.338028    0.416419      0.019608  
3     1796.20      4    Down       0    0.352113    0.387735      0.019608  
4     2021.48      4      Up       0    0.380282    0.452028      0.039216  
...       ...    ...     ...     ...         ...         ...           ...  
1889  2652.20      5  Middle       0    0.619718    0.286845      0.039216  
1890  1795.80      4    Down       0    0.380282    0.237389      0.078431  
1891  2624.40      4    Down       0    0.647887    0.346192      0.058824  
1892  1972.50      5    Down       0    0.197183    0.415430      0.078431  
1893  1574.40      5  Middle       0    0.211268    0.138477      0.039216  

[1894 rows x 110 columns]

## 모델
- logisticRegression 이용

## 평가
- predict 이용
- 평가수치 : F1 score