<a href="https://colab.research.google.com/github/skymined/study_AIs/blob/main/docs/MLs/classfications/01_LogisticRegression_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris # 꽃잎에 대한 데이터셋

In [ ]:
iris_X, iris_y = load_iris(return_X_y=True)

In [ ]:
type(iris_X), type(iris_y),iris_X.shape, iris_y.shape

(numpy.ndarray, numpy.ndarray, (150, 4), (150,))

In [ ]:
iris_X[:3], iris_X[-3:] # X, features

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([[6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]))

In [ ]:
iris_y[:3], iris_y[-3:]

(array([0, 0, 0]), array([2, 2, 2]))

## 모델 선택과 학습

In [ ]:
from sklearn import linear_model

In [ ]:
logisticRegression = linear_model.LogisticRegression() # 클래스화

In [ ]:
logisticRegression.fit(iris_X, iris_y)  # 교육시킬 때는 fit을 사용

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## 평가

In [ ]:
logisticRegression.predict(iris_X[:3])

array([0, 0, 0])

In [ ]:
logisticRegression.predict(iris_X[-3:])

array([2, 2, 2])

### 학습 방식 확인

In [ ]:
logisticRegression.predict(iris_X[:1]) # 가장 확률이 높은 값의 인덱스를 던져줌.

array([0])

In [ ]:
logisticRegression.predict_proba(iris_X[:1]) # 0에 있는 인덱스를 던져줌

array([[9.81799409e-01, 1.82005762e-02, 1.43509289e-08]])